[package]
name = "python-ron"
version = "0.2.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pyron"
crate-type = ["cdylib", "rlib"]

[dependencies]
ron = { version = "0.12.1", features = ["indexmap"] }
ron2 = { version = "0.3.0", features = ["integer128"] }
pyo3 = { version = "0.28.3", features = ["abi3-py310", "generate-import-lib"] }
