from typing import Any

def loads(s: str, preserve_structs: bool = False, preserve_class_names: bool = False, print_errors: bool = True) -> Any: ...
def load(
    path: str, preserve_structs: bool = False, preserve_class_names: bool = False, print_errors: bool = True
) -> Any: ...
def to_string(obj: Any) -> str: ...
